VERSION = "249.0-VELOCITY"
MAIN_TIMEFRAME = "1H"
EXECUTION_TIMEFRAME = "15m"

# 回調宏觀門檻
Z_SCORE_THRESHOLD = 1.2   # 回到 1.2，只抓強勢趨勢
ENTROPY_THRESHOLD = 0.7   # 提高有序度要求

# 執行過濾優化
COOLDOWN_PERIOD = 8       # 同幣種開單後，8 小時內不再重複開單
MIN_PROFIT_TO_BE = 2.0    # 獲利必須達到 2.0x ATR 才能觸發保本

# 基礎風險與交易參數 (保持引擎相容性)
BASE_RISK_PER_TRADE = 0.02
SCALING_OUT_RATIO = 0.5
TOTAL_FRICTION = 0.0010
MAX_DAILY_LOSS = 0.05
SL_ATR_MULT = 2.0
TP_ATR_MULT = 4.0
BE_ATR_TRIGGER = 2.0
