import os
import requests
from src.evaluate import get_full_report
from datetime import datetime

def create_github_issue(rsi_th=30, ema_f=50, ema_s=200, sl_mult=2, oos_passed=True, macd_confirm=True):
    report_content = get_full_report(rsi_th=rsi_th, ema_f=ema_f, ema_s=ema_s, sl_mult=sl_mult, macd_confirm=macd_confirm)
    title = f"[Strategy Iteration] Report - {datetime.now().strftime('%Y-%m-%d')}"

    if not oos_passed:
        title = f"⚠️ [Strategy Iteration] OOS Failed - {datetime.now().strftime('%Y-%m-%d')}"
        report_content = "### ⚠️ Out-of-Sample Verification Failed\n\n" + report_content
        report_content += "\n\n**Note**: This iteration did not pass the OOS test and was not deployed."

    # 使用 GitHub API 替代 gh CLI
    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPOSITORY", "sasojoy/ai_crypto_strategy")
    
    if not token:
        print("Skipping issue creation: GITHUB_TOKEN not found.")
        return

    url = f"https://api.github.com/repos/{repo}/issues"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }
    data = {
        "title": title,
        "body": report_content + "\n\n---\n*This report was automatically generated by the AI Crypto Strategy Bot.*",
        "labels": ["Strategy Iteration"]
    }

    try:
        response = requests.post(url, json=data, headers=headers)
        if response.status_code == 201:
            print(f"Successfully created issue: {response.json().get('html_url')}")
        else:
            print(f"Failed to create issue: {response.status_code} - {response.text}")
    except Exception as e:
        print(f"Error creating GitHub issue via API: {e}")

if __name__ == "__main__":
    create_github_issue()
